### ISSUE TITLE
wgAuthFlarumAutoCreate = ture; cause HTTP 500

### ISSUE THREAD

**Issue by brucekomike** [llaumgui/mw-auth-flarum#21]
Hello,

I've install this extension on my wiki, when that line is commented, every thing works well

when there is `$wgAuthFlarumAutoCreate = ture;` in my wiki setting, the site return 500.

the config can make all things go well is here
```
wfLoadExtension( 'AuthFlarum' );
$wgAuthFlarumUri = "https://mysite.example";
#$wgAuthFlarumAutoCreate = ture;
$wgAuthFlarumAutoCreateMinPost = 1;
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['sysop']['createaccount'] = false;
$wgGroupPermissions['*']['autocreateaccount'] = true;
```

below is my steps to install:
- Download and unzip
- Rename the folder
- add lines to wiki Localsettings.php file.
- restart apache webserver

system env:
- ubuntu 20.04
- apache2 (from ppa:ondrej/apache2)
- php8.3 ( from ppa:ondrej/php)

 it's strange that there is no line in `/var/log/apache2/error.log` report this error

**Comment by llaumgui** [comment]
Hum, it's a doc issue. Can you try with `true`instead of `ture` ?
